bug fixes
dandclark/BigInt pull request #7
Opened 2023-09-29 21:12 UTC by remdragon

avoid using signed integer index in for loop when terminating value is unsigned
check for malloc() returning NULL
detect overflow when converting BigInt to int
dedup BigInt_print()
BigInt_fprint() performance improvement

2023-10-03 04:11 UTC, dandclark requested changes
Thanks for the PR!

Left some comments from a first review pass. `make` is failing to build with clang because demo.c needs to be updated to handle the `BigInt_to_int` change, and there are some `unsigned char*` to `char*` conversions that yield warnings -- I left comments for those. Can you take a look?

2023-10-03 04:11 UTC, dandclark commented on BigInt.c
> +            errno = ENOMEM;
From my reading of the [malloc man page](https://www.man7.org/linux/man-pages/man3/malloc.3.html#:~:text=On%20error%2C%20these%20functions%20return%20NULL%20and%20set%20errno.) it should always set errno on failure, so I don't think it's necessary to manage errno like this.

2023-10-03 04:11 UTC, dandclark commented on BigInt.c
> +    while( count-- ) {
```suggestion
    while(count--) {
```

2023-10-03 04:11 UTC, dandclark commented on BigInt.h
> +BOOL BigInt_to_int(int* result, const BigInt* big_int);
```suggestion
BOOL BigInt_to_int(const BigInt* big_int, int* result);
```
This is nitpicky but I'd prefer to have the parameter order match the order of things like `BigInt_multiply_int` and match the fact that `BigInt` comes before `int` in the name of this function.

2023-10-03 04:11 UTC, dandclark commented on BigInt.c
> +    char* digits = new_big_int->digits;
```suggestion
    unsigned char* digits = new_big_int->digits;
```
gcc emits a `-Wpointer-sign` warning otherwise.

2023-10-03 04:11 UTC, dandclark commented on BigInt.c
> +    char* tgt = target->digits;
```suggestion
    unsigned char* tgt = target->digits;
```

2023-10-03 04:11 UTC, dandclark commented on BigInt.c
> +    const char* src = source->digits;
```suggestion
    unsigned const char* src = source->digits;
```

2023-10-03 04:11 UTC, dandclark commented on BigInt.c
> +    char* digits = target->digits;
```suggestion
    unsigned char* digits = target->digits;
```

2023-10-03 04:11 UTC, dandclark commented on BigInt.c
> +    const char* pa = &a->digits[count-1];
```suggestion
    unsigned const char* pa = &a->digits[count-1];
```

2023-10-03 04:11 UTC, dandclark commented on BigInt.c
> +    const char* pb = &b->digits[count-1];
```suggestion
    unsigned const char* pb = &b->digits[count-1];
```

2023-10-03 04:11 UTC, dandclark commented on BigInt.c
> +    const char* digits = big_int->digits;
```suggestion
    unsigned const char* digits = big_int->digits;
```

2023-10-03 04:11 UTC, dandclark commented on BigInt.c
> +    const char* base = big_int->digits;
```suggestion
    unsigned const char* base = big_int->digits;
```

2023-10-03 04:11 UTC, dandclark commented on BigInt.h
> +BOOL BigInt_assign(BigInt* target, const BigInt* source);
Would be helpful to update the header comments to say what the return value means for all these.

2023-10-03 13:51 UTC, remdragon commented on BigInt.h
> +BOOL BigInt_assign(BigInt* target, const BigInt* source);
Are you looking for "returns non-zero on success or 0 on failure", or are you looking something more like a list of possible reasons for the function to fail? I'm going with the former for now, but want to make sure I understand what you're requesting completely (BOOL implies "returns non-zero on success or 0 on failure" to me, which is why I'm unsure exactly what's being asked for here, sorry)

2023-10-03 13:53 UTC, remdragon commented
I was stupidly only testing with tinyc. I'm now testing with clang and gcc as well.

2023-10-05 03:30 UTC, dandclark requested changes
Thanks for the follow-ups, this is close to ready to merge.
Just had some remaining comments for: a failing test, a small bug in BigInt_fprintf, and a few misc nitpicks.

2023-10-05 03:30 UTC, dandclark commented on BigInt_test.c
> +    //BigInt_test_operations(999999999, 123456789);
```suggestion
    BigInt_test_operations(999999999, 123456789);
```
Looks like this last test still fails. I haven't had time to dig into it further yet but probably best to understand it before merging.

```
Testing basic 2-argument operations
Assertion failed: (BigInt_to_int(big_int_a, &result)), function BigInt_test_single_operation, file BigInt_test.c, line 172.
```

2023-10-05 03:30 UTC, dandclark commented on BigInt.h
> +BOOL BigInt_assign(BigInt* target, const BigInt* source);
What you've got now ("returns non-zero on success or 0 on failure") is good.

2023-10-05 03:30 UTC, dandclark commented on BigInt_test.c
> +    assert(BigInt_to_int(big_int, &value) && value  == 42);
```suggestion
    assert(BigInt_to_int(big_int, &value) && value == 42);
```

2023-10-05 03:30 UTC, dandclark commented on BigInt.c
> +        if(!errno) {
Same feedback as the other comment, it seems unnecessary to manage `errno` for `malloc` like this (or from `malloc_digits` since that's controlled in this code).

2023-10-05 03:30 UTC, dandclark commented on BigInt.c
> +    while( num_digits && !digits[num_digits-1] ){
```suggestion
    while(num_digits && !digits[num_digits-1]){
```

2023-10-05 03:30 UTC, dandclark commented on README.md
> +Get a normal int back from a BigInt with using BigInt_to_int; but be careful; if the BigInt doesn't fit in an int type, the function will return 0 and the output will be unchanged and
```suggestion
Get a normal int back from a BigInt with using BigInt_to_int; but be careful; if the BigInt doesn't fit in an int type, the function will return 0 and the value in the int argument will be undefined.
```

Looks like BigInt_to_int can trample on the out param prior to hitting an overflow condition, so probably safest to just say the output is undefined on failure.

2023-10-05 03:30 UTC, dandclark commented on BigInt.c
> +    if (big_int->is_negative) fputc('0', dest);
```suggestion
    if (big_int->is_negative) fputc('-', dest);
```

2023-10-05 03:30 UTC, dandclark commented on BigInt.c
> +unsigned char* okay_digits(unsigned char* digits, unsigned int num_digits) {
This is clever. Maybe worth a brief comment at the top of the redzone block outlining the checking scheme?

2023-10-05 03:35 UTC, remdragon commented on BigInt_test.c
> +    //BigInt_test_operations(999999999, 123456789);
The test is failing because it can't be converted back to int. 999999999 * 123456789 doesn't fit into a 32-bit int.

2023-10-06 02:25 UTC, dandclark commented on BigInt_test.c
> +    //BigInt_test_operations(999999999, 123456789);
Ah, I see.

2023-10-06 02:26 UTC, dandclark approved these changes
Thanks again for the PR!

2023-10-06 02:28 UTC, merged